/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.expensetracker;

import javax.persistence.EntityManager;
import javax.persistence.Persistence;

import com.expensetracker.db.Expense;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Expense expense = new Expense();
        expense.setName("recharge");
        EntityManager em = Persistence.createEntityManagerFactory("expenseTracker").createEntityManager();
        em.persist(expense);
    }
}
